export const INSTAGRAM_SOURCES = [
  // Town / tourism pages
  { handle: "visitmargaretvilleny", town: "Margaretville" },
  { handle: "roxburyinthecatskills", town: "Roxbury" },
  { handle: "visitfleischmannsny", town: "Fleischmanns" },
  { handle: "tannersville_ny", town: "Tannersville" },
  { handle: "livingstonmanorny", town: "Livingston Manor" },
  { handle: "catskillhappenings", town: "Catskill" },
  { handle: "visitcatskills" },
  { handle: "sullivancatskills" },
  { handle: "catskilltourism" },
  { handle: "hudsonvalleyevents" },
  { handle: "kingstonhappenings", town: "Kingston" },
  { handle: "phoenicianys", town: "Phoenicia" },
  // Music venues & performance spaces
  { handle: "colonywoodstockny", town: "Woodstock" },
  { handle: "bearsvilletheater", town: "Woodstock" },
  { handle: "levonhelmstudios", town: "Woodstock" },
  { handle: "maverickconcerts", town: "Woodstock" },
  { handle: "tinkerstreetcinema", town: "Woodstock" },
  { handle: "tubbyskingston", town: "Kingston" },
  { handle: "assemblykingston", town: "Kingston" },
  { handle: "theavalonlounge", town: "Catskill" },
  { handle: "lumberyard_catskill", town: "Catskill" },
  { handle: "basilicahudson", town: "Hudson" },
  { handle: "helsinkihudson", town: "Hudson" },
  { handle: "hudsonhallny", town: "Hudson" },
  { handle: "tsl_hudson", town: "Hudson" },
  { handle: "thelocalsaugerties", town: "Saugerties" },
  { handle: "thepartitionbar", town: "Saugerties" },
  { handle: "catskillmountainfoundation", town: "Hunter" },
  { handle: "bethelwoodscenter", town: "Bethel" },
  { handle: "theemeraldballroom", town: "Narrowsburg" },
  { handle: "printhouseny", town: "Fleischmanns" },
  { handle: "rosendaletheatre", town: "Rosendale" },
  { handle: "citywineryhv", town: "Montgomery" },
  { handle: "stissingcenter", town: "Pine Plains" },
  // Breweries, cideries, wineries, distilleries
  { handle: "dear.native.grapes", town: "Walton" },
  { handle: "uniongrovedistillery", town: "Arkville" },
  { handle: "lastingjoybrewery", town: "Margaretville" },
  { handle: "arrowoodfarms", town: "Accord" },
  { handle: "keeganales", town: "Kingston" },
  { handle: "thecatskillbrewery", town: "Livingston Manor" },
  { handle: "roscoebeercompany", town: "Roscoe" },
  { handle: "upward.brewing", town: "Livingston Manor" },
  { handle: "wayside_cider", town: "Andes" },
  { handle: "sunkencitycider", town: "Gilboa" },
  { handle: "awestruckciders", town: "Walton" },
  { handle: "mountainkingbrewing", town: "Windham" },
  { handle: "suarezfamilybrewery", town: "Hudson" },
  { handle: "returnbrewing", town: "Hudson" },
  { handle: "seminaryhillny", town: "Callicoon" },
  { handle: "subversivebeer", town: "Catskill" },
  // Restaurants, bars & hotels with events
  { handle: "thebelvedereinn", town: "Stamford" },
  { handle: "pearlmoonwoodstock", town: "Woodstock" },
  { handle: "roughdraftny", town: "Kingston" },
  { handle: "stockadetavern", town: "Kingston" },
  { handle: "huttonbrickyards", town: "Kingston" },
  { handle: "forelandcatskill", town: "Catskill" },
  { handle: "hilocatskill", town: "Catskill" },
  { handle: "theandeshotel", town: "Andes" },
  { handle: "westerncallicoon", town: "Callicoon" },
  { handle: "theheronny", town: "Narrowsburg" },
  { handle: "theoutpost97", town: "Pond Eddy" },
  { handle: "binnekilltavern", town: "Margaretville" },
  { handle: "odawinegarden", town: "Margaretville" },
  { handle: "lastchancenow", town: "Tannersville" },
  { handle: "thedalepizza", town: "Mountaindale" },
  { handle: "thejunctionroscoe", town: "Roscoe" },
  { handle: "thearnoldhouse", town: "Livingston Manor" },
  { handle: "northbranchinn", town: "North Branch" },
  { handle: "foxfiremountainhouse", town: "Mt Tremper" },
  { handle: "urbancowboylodge", town: "Big Indian" },
  { handle: "cochectonpumphouse", town: "Cochecton" },
  { handle: "flyinggoosetavern" },
  { handle: "stewarthouseny", town: "Athens" },
  { handle: "callicoonhills", town: "Callicoon" },
  // Arts, galleries & cultural spaces
  { handle: "catskillpines", town: "Mt Tremper" },
  { handle: "westwindorchard", town: "Accord" },
  { handle: "phoeniciaplayhouse", town: "Phoenicia" },
  { handle: "bushelcollective", town: "Delhi" },
  { handle: "woodstockplayhouse", town: "Woodstock" },
  { handle: "opusforty", town: "Saugerties" },
  { handle: "catskillartspace", town: "Livingston Manor" },
  { handle: "upstate_films", town: "Saugerties" },
  { handle: "roxburyartsgroup", town: "Roxbury" },
  { handle: "dvartsalliance", town: "Narrowsburg" },
  { handle: "waamart", town: "Woodstock" },
  { handle: "woodstock_byrdcliffe_guild", town: "Woodstock" },
  { handle: "thomascolesite", town: "Catskill" },
  { handle: "hawkandhive", town: "Andes" },
  { handle: "longyeargallery", town: "Margaretville" },
  { handle: "woodstockfilmfestival", town: "Woodstock" },
  { handle: "callicoontheater", town: "Callicoon" },
  { handle: "thewaltontheatre", town: "Walton" },
  // Farmers markets
  { handle: "kingstonfarmersmarket", town: "Kingston" },
  { handle: "phoeniciafarmersmarket", town: "Phoenicia" },
  { handle: "callicoonfarmersmarket", town: "Callicoon" },
  { handle: "catskillfarmersmarket", town: "Catskill" },
  // Farms & sanctuaries
  { handle: "catskill_animal_sanctuary", town: "Saugerties" },
  // Libraries
  { handle: "phoenicialibrary", town: "Phoenicia" },
  { handle: "woodstocklibrary", town: "Woodstock" },
  // Festivals
  { handle: "greyfoxbluegrass", town: "Oak Hill" },
];

export const WEB_SOURCES = [
  {
    name: "Catskill Crew",
    discoverUrl: "https://catskillcrew.beehiiv.com/",
    type: "newsletter-archive",
  },
  {
    name: "VISITvortex",
    urls: ["https://visitvortex.com/events"],
    type: "calendar",
  },
  {
    name: "HVNY",
    urls: ["https://hvny.info/calendar"],
    type: "calendar",
  },
  {
    name: "Great Northern Catskills",
    urls: ["https://www.greatnortherncatskills.com/events"],
    type: "calendar",
  },
  {
    name: "Chronogram",
    urls: [
      "https://calendar.chronogram.com/hudsonvalley/EventSearch?v=d",
    ],
    type: "calendar",
  },
  {
    name: "Catskill Mountain Foundation",
    urls: ["https://www.catskillmtn.org/performances/"],
    type: "calendar",
  },
  {
    name: "Great Western Catskills",
    tockifyCalendar: "greatwesterncatskills",
    type: "tockify",
  },
  {
    name: "AllEvents.in",
    urls: [
      "https://allevents.in/catskill/all",
      "https://allevents.in/kingston-ny/all",
      "https://allevents.in/woodstock/all",
      "https://allevents.in/hudson-ny/all",
      "https://allevents.in/saugerties/all",
      "https://allevents.in/phoenicia/all",
      "https://allevents.in/andes/all",
      "https://allevents.in/margaretville/all",
      "https://allevents.in/windham-ny/all",
      "https://allevents.in/hunter-ny/all",
      "https://allevents.in/tannersville/all",
      "https://allevents.in/delhi-ny/all",
      "https://allevents.in/livingston-manor/all",
    ],
    type: "calendar",
  },
];
