// `venue` names the one venue an account runs, so its posts are placed there under that name,
// even when a post uses a nickname. Accounts for several venues (or a whole town) leave it out.
export const INSTAGRAM_SOURCES = [
  // Town / tourism pages
  { handle: "visitmargaretvilleny", town: "Margaretville" },
  { handle: "roxburyinthecatskills", town: "Roxbury" },
  { handle: "visitfleischmannsny", town: "Fleischmanns" },
  { handle: "tannersville_ny", town: "Tannersville" },
  { handle: "livingstonmanorny", town: "Livingston Manor" },
  { handle: "catskillhappenings", town: "Catskill" },
  { handle: "sullivancatskills" },
  { handle: "hudsonvalleyevents" },
  { handle: "kingstonhappenings", town: "Kingston" },
  { handle: "phoenicianys", town: "Phoenicia" },
  // Music venues & performance spaces
  { handle: "colonywoodstockny", town: "Woodstock", venue: "Colony" },
  { handle: "bearsvilletheater", town: "Woodstock", venue: "Bearsville Theater" },
  { handle: "levonhelmstudios", town: "Woodstock", venue: "Levon Helm Studios" },
  { handle: "maverickconcerts", town: "Woodstock", venue: "Maverick Concert Hall" },
  { handle: "tinkerstreetcinema", town: "Woodstock", venue: "Tinker Street Cinema" },
  { handle: "tubbyskingston", town: "Kingston", venue: "Tubby's" },
  { handle: "assemblykingston", town: "Kingston", venue: "Assembly Kingston" },
  { handle: "theavalonlounge", town: "Catskill", venue: "Avalon Lounge" },
  { handle: "lumberyard_catskill", town: "Catskill", venue: "Lumberyard" },
  { handle: "basilicahudson", town: "Hudson", venue: "Basilica Hudson" },
  { handle: "helsinkihudson", town: "Hudson", venue: "Helsinki Hudson" },
  { handle: "hudsonhallny", town: "Hudson", venue: "Hudson Hall" },
  { handle: "tsl_hudson", town: "Hudson", venue: "Time & Space Limited" },
  { handle: "thelocalsaugerties", town: "Saugerties", venue: "The Local" },
  { handle: "thepartitionbar", town: "Saugerties", venue: "The Partition" },
  { handle: "catskillmountainfoundation", town: "Hunter" },
  { handle: "bethelwoodscenter", town: "Bethel", venue: "Bethel Woods Center for the Arts" },
  { handle: "theemeraldballroom", town: "Narrowsburg", venue: "The Emerald Ballroom" },
  { handle: "printhouseny", town: "Fleischmanns", venue: "Printhouse" },
  { handle: "rosendaletheatre", town: "Rosendale", venue: "Rosendale Theatre" },
  { handle: "citywineryhv", town: "Montgomery", venue: "City Winery Hudson Valley" },
  { handle: "stissingcenter", town: "Pine Plains", venue: "Stissing Center" },
  // Breweries, cideries, wineries, distilleries
  { handle: "dear.native.grapes", town: "Walton", venue: "Dear Native Grapes" },
  { handle: "uniongrovedistillery", town: "Arkville", venue: "Union Grove Distillery" },
  { handle: "lastingjoybrewery", town: "Tivoli", venue: "Lasting Joy Brewery" },
  { handle: "arrowoodfarms", town: "Accord", venue: "Arrowood Farms" },
  { handle: "keeganales", town: "Kingston", venue: "Keegan Ales" },
  { handle: "thecatskillbrewery", town: "Livingston Manor", venue: "Catskill Brewery" },
  { handle: "roscoebeercompany", town: "Roscoe", venue: "Roscoe Beer Company" },
  { handle: "upward.brewing", town: "Livingston Manor", venue: "Upward Brewing" },
  { handle: "wayside_cider", town: "Andes", venue: "Wayside Cider" },
  { handle: "sunkencitycider", town: "Gilboa", venue: "Sunken City Cider" },
  { handle: "awestruckciders", town: "Sidney", venue: "Awestruck Ciders" },
  { handle: "mountainkingbrewing", town: "Windham", venue: "Mountain King Brewing" },
  { handle: "suarezfamilybrewery", town: "Hudson", venue: "Suarez Family Brewery" },
  { handle: "returnbrewing", town: "Hudson", venue: "Return Brewing" },
  { handle: "seminaryhillny", town: "Callicoon", venue: "Seminary Hill" },
  { handle: "subversivebeer", town: "Catskill", venue: "Subversive Malting + Brewing" },
  // Restaurants, bars & hotels with events
  { handle: "fullmoonresort", town: "Big Indian", venue: "Full Moon Resort" },
  { handle: "belleayre", town: "Highmount", venue: "Belleayre Mountain" },
  { handle: "thebelvedereinn", town: "Stamford", venue: "The Belvedere Inn" },
  { handle: "pearlmoonwoodstock", town: "Woodstock", venue: "Pearl Moon" },
  { handle: "roughdraftny", town: "Kingston", venue: "Rough Draft" },
  { handle: "stockadetavern", town: "Kingston", venue: "Stockade Tavern" },
  { handle: "huttonbrickyards", town: "Kingston", venue: "Hutton Brickyards" },
  { handle: "forelandcatskill", town: "Catskill", venue: "Foreland" },
  { handle: "theandeshotel", town: "Andes", venue: "The Andes Hotel" },
  { handle: "westerncallicoon", town: "Callicoon", venue: "The Western" },
  { handle: "theheronny", town: "Narrowsburg", venue: "The Heron" },
  { handle: "theoutpost97", town: "Pond Eddy", venue: "The Outpost" },
  { handle: "binnekilltavern", town: "Margaretville", venue: "Binnekill Tavern" },
  { handle: "odawinegarden", town: "Margaretville", venue: "Oda Wine Garden" },
  { handle: "lastchancenow", town: "Tannersville", venue: "Last Chance Antiques & Cheese Cafe" },
  { handle: "thedalepizza", town: "Mountaindale", venue: "The Dale" },
  { handle: "thejunctionroscoe", town: "Roscoe", venue: "The Junction" },
  { handle: "thearnoldhouse", town: "Livingston Manor", venue: "The Arnold House" },
  { handle: "northbranchinn", town: "North Branch", venue: "North Branch Inn" },
  { handle: "foxfiremountainhouse", town: "Mt Tremper", venue: "Foxfire Mountain House" },
  { handle: "urbancowboylodge", town: "Big Indian", venue: "Urban Cowboy Lodge" },
  { handle: "cochectonpumphouse", town: "Cochecton", venue: "Cochecton Pump House" },
  { handle: "flyinggoosetavern", town: "Kerhonkson", venue: "Flying Goose Tavern" },
  { handle: "stewarthouseny", town: "Athens", venue: "Stewart House" },
  { handle: "callicoonhills", town: "Callicoon", venue: "Callicoon Hills" },
  // Arts, galleries & cultural spaces
  { handle: "ashokancenter", town: "Olivebridge", venue: "Ashokan Center" },
  { handle: "catskillcenter", town: "Arkville" },
  { handle: "catskillpines", town: "Mt Tremper", venue: "Catskill Pines" },
  { handle: "westwindorchard", town: "Accord", venue: "Westwind Orchard" },
  { handle: "phoeniciaplayhouse", town: "Phoenicia", venue: "Phoenicia Playhouse" },
  { handle: "bushelcollective", town: "Delhi", venue: "Bushel Collective" },
  { handle: "pillow_fort_arts_center", town: "Andes", venue: "Pillow Fort Arts Center" },
  { handle: "thedcspa", town: "Margaretville" },
  { handle: "opusforty", town: "Saugerties", venue: "Opus 40" },
  { handle: "catskillartspace", town: "Livingston Manor", venue: "Catskill Art Space" },
  { handle: "upstate_films", town: "Saugerties" },
  { handle: "roxburyartsgroup", town: "Roxbury" },
  { handle: "dvartsalliance", town: "Narrowsburg" },
  { handle: "waamart", town: "Woodstock", venue: "Woodstock Artists Association & Museum" },
  { handle: "woodstock_byrdcliffe_guild", town: "Woodstock" },
  { handle: "thomascolesite", town: "Catskill", venue: "Thomas Cole National Historic Site" },
  { handle: "hawkandhive", town: "Andes" },
  { handle: "longyeargallery", town: "Margaretville", venue: "Longyear Gallery" },
  { handle: "woodstockfilmfestival", town: "Woodstock" },
  { handle: "callicoontheater", town: "Callicoon", venue: "Callicoon Theater" },
  { handle: "thewaltontheatre", town: "Walton", venue: "Walton Theatre" },
  // Farmers markets
  { handle: "pakatakanfarmersmarket", town: "Halcottsville", venue: "Pakatakan Farmers Market" },
  { handle: "kingstonfarmersmarket", town: "Kingston", venue: "Kingston Farmers Market" },
  { handle: "phoeniciafarmersmarket", town: "Phoenicia", venue: "Phoenicia Farmers Market" },
  { handle: "callicoonfarmersmarket", town: "Callicoon", venue: "Callicoon Farmers Market" },
  { handle: "catskillfarmersmarket", town: "Catskill", venue: "Catskill Farmers Market" },
  // Farms & sanctuaries
  { handle: "catskill_animal_sanctuary", town: "Saugerties", venue: "Catskill Animal Sanctuary" },
  // Libraries
  { handle: "phoenicialibrary", town: "Phoenicia", venue: "Phoenicia Library" },
  { handle: "woodstocklibrary", town: "Woodstock", venue: "Woodstock Public Library" },
  // Festivals
  { handle: "greyfoxbluegrass", town: "Oak Hill" },
];

export const WEB_SOURCES = [
  {
    name: "Catskill Crew",
    discoverUrl: "https://catskillcrew.beehiiv.com/",
    type: "newsletter-archive",
  },
  {
    name: "VISITvortex",
    urls: ["https://visitvortex.com/events"],
    type: "calendar",
  },
  {
    name: "HVNY",
    urls: ["https://hvny.info/calendar"],
    type: "calendar",
  },
  {
    name: "Great Northern Catskills",
    urls: ["https://www.greatnortherncatskills.com/events"],
    type: "calendar",
  },
  {
    name: "Chronogram",
    urls: [
      "https://calendar.chronogram.com/hudsonvalley/EventSearch?v=d",
    ],
    type: "calendar",
  },
  {
    name: "Catskill Mountain Foundation",
    urls: ["https://www.catskillmtn.org/performances/"],
    type: "calendar",
  },
  {
    name: "Great Western Catskills",
    tockifyCalendar: "greatwesterncatskills",
    type: "tockify",
  },
  {
    name: "AllEvents.in",
    // Read from each town page's schema.org data; the LLM only for a page without it.
    structured: true,
    urls: [
      "https://allevents.in/catskill/all",
      "https://allevents.in/kingston-ny/all",
      "https://allevents.in/woodstock-ny/all",
      "https://allevents.in/hudson-ny/all",
      "https://allevents.in/saugerties/all",
      "https://allevents.in/phoenicia/all",
      "https://allevents.in/andes/all",
      "https://allevents.in/margaretville/all",
      "https://allevents.in/windham-ny/all",
      "https://allevents.in/hunter-ny/all",
      "https://allevents.in/tannersville-ny/all",
      "https://allevents.in/delhi-ny/all",
      "https://allevents.in/livingston-manor/all",
      "https://allevents.in/rhinebeck/all",
      "https://allevents.in/new-paltz/all",
      "https://allevents.in/narrowsburg/all",
      "https://allevents.in/callicoon/all",
    ],
    type: "calendar",
  },
  {
    name: "Eventbrite",
    structured: true,
    // robots.txt allows these pages and asks for a crawl delay of up to 2s.
    delayMs: 2000,
    // Town pages overlap heavily (Woodstock events show up on most); these are the ones that
    // added events the others didn't when measured.
    urls: [
      "https://www.eventbrite.com/d/ny--kingston/all-events/",
      "https://www.eventbrite.com/d/ny--kingston/all-events/?page=2",
      "https://www.eventbrite.com/d/ny--hudson/all-events/",
      "https://www.eventbrite.com/d/ny--delhi/all-events/",
      "https://www.eventbrite.com/d/ny--phoenicia/all-events/",
      "https://www.eventbrite.com/d/ny--livingston-manor/all-events/",
      "https://www.eventbrite.com/d/ny--woodstock/all-events/",
    ],
    type: "calendar",
  },
];
